/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Titanium SDK
 * Copyright TiDev, Inc. 04/07/2022-Present
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package ti.android.share;

import org.appcelerator.kroll.KrollModule;
import org.appcelerator.kroll.annotations.Kroll;
import org.appcelerator.titanium.TiApplication;
import java.util.HashMap;

@Kroll.module(name="TiAndroidShare", id="ti.android.share")
public class TiAndroidShareModule extends KrollModule {

	private static final String TAG = "TiAndroidShare";

	public TiAndroidShareModule() {
		super();
	}

	@Kroll.onAppCreate
	public static void onAppCreate(TiApplication app) {
		// Module initialized
	}

	@Kroll.method
	@SuppressWarnings("unchecked")
	public void share(Object params) {
		if (params instanceof HashMap) {
			ShareProxy.share((HashMap<String, Object>)params, this);
		}
	}
}